# Generated by Django 3.1.3 on 2020-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
    ]
