# Generated by Django 3.1.3 on 2020-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201130_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='post_files'),
        ),
    ]
