# Generated by Django 3.1.3 on 2020-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201130_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shorttext',
            field=models.CharField(default='', max_length=200),
        ),
    ]
